ut/urls.py
from django.conf.urls.defaults import *
from sandbox.ut.views import *

urlpatterns = patterns('',
    url(r'games/(?P<hash>[-\w]+)/$',
        view=game_detail,
        name='game_detail'),

    url(r'games/$',
        view=game_list,
        name='game_list'),

    url(r'players/(?P<username>[-\w]+)/$',
        view=player_detail,
        name='player_detail'),

    url(r'players/(?P<username>[-\w]+)/kd/$',
        view=player_kill_to_death_ratio,
        name='player_kill_to_death_ratio'),
        
    url(r'players/(?P<username>[-\w]+)/kdave/$',
        view=player_kill_to_death_ratio_ave,
        name='player_kill_to_death_ratio_ave'),

    url(r'players/(?P<username>[-\w]+)/kd/json/$',
        view=player_kill_to_death_ratio_json,
        name='player_kill_to_death_ratio_json'),
    
    url(r'players/(?P<username>[-\w]+)/kdave/json/$',
        view=player_kill_to_death_ratio_ave_json,
        name='player_kill_to_death_ratio_ave_json'),
    
    url(r'players/$',
        view=player_list,
        name='player_list'),

    url(r'weapons/(?P<ut_name>[-\w]+)/$',
        view=weapon_detail,
        name='weapon_detail'),

    url(r'weapons/$',
        view=weapon_list,
        name='weapon_list'),
)

ut/models.py
from django.db import models
from django.db.models import permalink


class GameManager(models.Manager):
    def get_games_with_player(self, username):
        return self.filter(models.Q(kills__victim__username=username) | models.Q(kills__killer__username=username)).distinct()

class Game(models.Model):
    details = models.TextField()
    hash = models.TextField()

    objects = GameManager()

    _players = None

    @property
    def players(self):
        if self._players is None:
            kills = Kill.objects.filter(game=self)
            for kill in kills:
                players.append(kill.killer)
                players.append(kill.victim)
            self._players = list(set(players))
        return self._players

    def __unicode__(self):
        return self.hash

    @permalink
    def get_absolute_url(self):
        return ('game_detail', None, {
            'hash': self.hash,
        })

class Weapon(models.Model):
    name = models.CharField(max_length=255, null=True)
    ut_name = models.CharField(max_length=255)

    _kill_counts = None

    def __unicode__(self):
        return self.ut_name

    @permalink
    def get_absolute_url(self):
        return ('weapon_detail', None, {
            'ut_name': self.ut_name,
        })

    def get_kills_by_player(self):
        if self._kill_counts is None:
            kill_counts = []
            players = Player.objects.all().order_by('username')
            for player in players:
                kills = Kill.objects.filter(weapon=self, killer=player).count()
                if kills:
                    kill_counts.append({
                        'killer': player,
                        'username': player.username,
                        'count': kills,
                    })
        return self.kill_counts

class Player(models.Model):
    username = models.CharField(max_length=255)
    kills = models.ManyToManyField("self", through="Kill", symmetrical=False)

    _victims = None
    _weapon_counts = None

    def __unicode__(self):
        return self.username

    @permalink
    def get_absolute_url(self):
        return ('player_detail', None, {
            'username': self.username,
        })

    def get_games_played(self):
        return -1

    def get_kill_ratio(self):
        return float(Kill.objects.filter(killer=self).count() + 1) / float(Kill.objects.filter(victim=self).count() + 1)

    def get_victims(self):
        if self._victims_count is None:
            victim_count = []
            players = Player.objects.all().order_by('username')
            for player in players:
                kills = Kill.objects.filter(killer=self, victim=player).count()
                if kills:
                    victim_count.append(
                        {
                            'victim': player,
                            'count': kills,
                        }
                    )
        return self._victim_count

    def get_kills_by_weapon(self):
        if self._weapon_counts is None:
            weapon_counts = []
            weapons = Weapon.objects.all()
            for weapon in weapons:
                kills = Kill.objects.filter(killer=self, weapon=weapon).count()
                if kills:
                    weapon_counts.append({
                        'weapon': weapon,
                        'count': kills,
                    })
        return self._weapon_counts

class Kill(models.Model):
    killer = models.ForeignKey(Player, related_name="victims")
    victim = models.ForeignKey(Player, related_name="killers")
    weapon = models.ForeignKey(Weapon)
    game = models.ForeignKey(Game, related_name="kills")

    def __unicode__(self):
        return "%s killed by %s with %s" % (self.victim, self.killer, self.weapon)

class BodyPart(models.Model):
    name = models.CharField(max_length=255, null=True)
    ut_name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.ut_name

class Hit(models.Model):
    attacker = models.ForeignKey(Player, related_name="hits_made")
    casualty = models.ForeignKey(Player, related_name="hits_incurred")
    body_part = models.ForeignKey(BodyPart)
    game = models.ForeignKey(Game, related_name="hits_per_game")

    def __unicode__(self):
        return "%s was hit by %s in the %s" % (self.victim.username, self.attacker.username, self.body_part_ut_name)

ut/templates/ut/game_detail.html
{% extends "base.html" %}


{% block body_class %}game{% endblock %}


{% block content_title %}
<h3>{{object}}</h3>
{% endblock %}


{% block content %}
<dl>
    <dt>id</dt>
    <dd>{{object.id}}</dd>
    <dt>hash</dt>
    <dd>{{object.hash}}</dd>
    <dt>details</dt>
    <dd>{{object.details}}</dd>
</dl>
{% endblock %}

ut/templates/ut/game_list.html
{% extends "base.html" %}


{% block body_class %}game{% endblock %}


{% block content_title %}
<h3>Games</h3>
{% endblock %}


{% block content %}
<ul>
{% for object in object_list %}
    <li><a href="{{object.get_absolute_url}}">{{object.hash}}</a></li>
{% endfor %}
</ul>
{% endblock %}

ut/templates/ut/graph.html
<html>
    <head>        
        <style type="text/css">
            body{ margin: 0px; padding: 0px; }
            #menu
            {
                position: absolute;    
                left: 0px;
                top: 0px;
                height: 80px;
                background-color: transparent;            
            }
            #overlay
            {
                position: absolute;
                left: 0px;
                top: 90px;        
                z-index: 100;            
                background: transparent;    
                border: #555555 solid 1px;                    
            }            
            #evalInfo
            {
                border: #aaaaaa solid 1px;
                background-color: #eeeeee;
                display: none;
                position: absolute;
                font: normal 11px arial;
            }
            span { border: #cccccc solid 1px; padding: 8px 6px 2px 2px; font-size: 10px;}
            form { margin: 0px; padding: 0px; display: inline; }
        </style>        
        <script type="text/javascript" src="http://media.seanbleier.com/js/jquery.js"></script>
    </head>
    <body onload="initialize('./json/');">
        <div id="menu">
            <fieldset>
                <legend>Tools</legend>
                <form id="toolOptions" name="toolOptions">                                    
                    <input type="checkbox" name="evaluate" id="evaluate"  />
                    <label>Evaluate</label>            
                    <input type="checkbox" name="zoom" id="zoom"  />
                    <label>Zoom</label>                    
                    <span>
                        <input type="radio" name="zoomType" id="zoomClick" value="Click" checked />
                        <label>Zoom</label>
                        <input type="radio" name="zoomType" id="zoomSelection" value="Selection" />
                        <label>Zoom Selection</label>        
                    </span>&nbsp;
                    <span>                
                        <input type="radio" name="zoomDir" id="zoomDirIn" value="In" checked />
                        <label>Zoom In</label>
                        <input type="radio" name="zoomDir" id="zoomDirOut" value="Out"  />
                        <label>Zoom Out</label>
                    </span>
                </form>
            </fieldset>
        </div>
        <div id="overlay"></div>
        <div id="evalInfo"></div>
        <script type="text/javascript" src="http://media.seanbleier.com/js/display_manager.js" /></script>
        <script type="text/javascript" src="http://media.seanbleier.com/js/event_manager.js" /></script>
        <script type="text/javascript" src="http://media.seanbleier.com/js/canvas.js" /></script>        
    </body>
</html>

ut/templates/ut/player_detail.html
{% extends "base.html" %}


{% block body_class %}player{% endblock %}


{% block content_title %}
<h3>{{ object.username }}</h3>
{% endblock %}


{% block content %}
<dl>
    <dt>id</dt>
    <dd>{{object.id}}</dd>

    <dt>username</dt>
    <dd>{{object.username}}</dd>

    <dt>total kills</dt>
    <dd>{{object.kills.count}}</dd>

    <dt>has killed</dt>
    <dd>{{object.victims.count}}</dd>

    <dt>has been killed</dt>
    <dd>{{object.killers.count}}</dd>

    <dt>games played</dt>
    <dd>{{object.get_games_played}}</dd>

    <dt>kill ratio</dt>
    <dd>{{object.get_kill_ratio}}</dd>
</dl>

<h3><a href="./kd/">Graph of Kill to Death Ratio</a></h3>
<h3><a href="./kdave/">Graph of Kill to Death Ratio running average</a></h3>

<h3>Kills by Victim (including yourself)</h3>

<table>
    <thead>
        <tr>
            <th>victim username</th>
            <th>total deaths</th>
        </tr>
    </thead>
    <tbody>
{% for victim in object.get_victims %}
        <tr class="{% cycle "even" "odd" %}">
            <td><a href="{{victim.victim.get_absolute_url}}">{{victim.victim.username}}</td>
            <td>{{victim.count}}</a></td>
        </tr>
{% endfor %}
    </tbody>
</table>


<h3>Kills by Weapon</h3>

<table>
    <thead>
        <tr>
            <th>weapon</th>
            <th>total kills</th>
        </tr>
    </thead>
    <tbody>
{% for weapon in object.get_kills_by_weapon %}
        <tr class="{% cycle "even" "odd" %}">
            <td><a href="{{weapon.weapon.get_absolute_url}}">{{weapon.weapon.ut_name}}</td>
            <td>{{weapon.count}}</a></td>
        </tr>
{% endfor %}
    </tbody>
</table>
{% endblock %}

ut/templates/ut/player_list.html
{% extends "base.html" %}


{% block body_class %}player{% endblock %}


{% block content_title %}
<h3>Players</h3>
{% endblock %}


{% block content %}
<ul>
{% for object in object_list %}
    <li><a href="{{object.get_absolute_url}}">{{object.username}}</a></li>
{% endfor %}
</ul>
{% endblock %}

ut/templates/ut/stats.html
{% extends "base.html" %}
{% block content_title %}
<h1>Where Ponies come to die - the Coral of Death</h1>
<h2>Global Stats</h2>
{% endblock %}>
{% block content %} 
    {% load ut %}
    {% get_players as killers victims %}
    <table cellpadding="2" cellspacing="1" id="global-stats" class="tablesorter">
    <thead>
    <tr>
    <th class="header"><strong>Victims</strong></th>
    {% for killer in killers %}
        <th>{{ killer.username }}</th>
    {% endfor %}
    <th><strong>Total Deaths</strongh></th>
    <th><strong>Kill / Death Ratio</strong></th>
    </tr>
    </thead>
    <tbody>
    {% for victim in victims %}
        <tr class="{% cycle "even" "odd" %}">
        <td><a href="ut/players/{{ victim.username }}/">{{ victim.username }}</a></td>
        {% for killer in killers %}
        <td>{% get_kills killer victim %}</td>
        {% endfor %}
        <td><strong>{% get_total_deaths victim %}</strong></td>
        <td><strong>{% get_kill_ratio victim %}</td>
        </tr>
    {% endfor %}
    </tbody>
    <tfoot>
    <tr>
    <td><strong>Total Kills<strong></td>
    {% for killer in killers %}
        <td><strong>{% get_total_kills killer %}</strong></td>
    {% endfor %}
    <td>&nbsp;</td>
    <td colspan="2">&nbsp;</td>
    </tfoot>
    </table>
    <hr />
    {% for game in games %}
        {% get_players game as killers victims %}
        <table cellpadding="2" cellspacing="1" class="tablesorter">
        <thead>
        <tr>
        <th class="header"><strong>Victims</strong></th>
        {% for killer in killers %}
            <th class="header">{{ killer.username }}</th>
        {% endfor %}
        <th class="header"><strong>Total Deaths</strong></th>
        <th class="header"><strong>Kill / Death Ratio</strong></th>
        </tr>
        </thead>
        <tbody>
        {% for victim in victims %}
            <tr class="{% cycle "even" "odd" %}">
            <td>{{ victim.username }}</td>
            {% for killer in killers %}
            <td>{% get_kills killer victim game %}</td>
            {% endfor %}
            <td><strong>{% get_total_deaths victim game %}</strong></td>
            <td><strong>{% get_kill_ratio victim game %}</td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
        <td><strong>Total Kills<strong></td>
        {% for killer in killers %}
            <td><strong>{% get_total_kills killer game %}</strong></td>
        {% endfor %}
        <td>&nbsp;</td>
        <td colspan="2">&nbsp;</td>
        </tfoot>
        </table>
    {% endfor %}
{% endblock %}

ut/templates/ut/weapon_detail.html
{% extends "base.html" %}


{% block body_class %}weapon{% endblock %}


{% block content_title %}
<h3>{{object.ut_name}}</h3>
{% endblock %}


{% block content %}
<dl>
    <dt>id</dt>
    <dd>{{object.id}}</dd>

    <dt>username</dt>
    <dd>{{object.name}}</dd>

    <dt>ut_name</dt>
    <dd>{{object.ut_name}}</dd>

    <dt>total kills</dt>
    <dd>{{object.kill_set.count}}</dd>
</dl>


<h3>Kills by Player</h3>

<table>
    <thead>
        <tr>
            <th>username</th>
            <th>total kills</th>
        </tr>
    </thead>
    <tbody>
{% for player in object.get_kills_by_player %}
        <tr class="{% cycle "even" "odd" %}">
            <td><a href="{{player.killer.get_absolute_url}}">{{player.killer.username}}</td>
            <td>{{player.count}}</a></td>
        </tr>
{% endfor %}
    </tbody>
</table>
{% endblock %}

ut/templates/ut/weapon_list.html
{% extends "base.html" %}


{% block body_class %}weapon{% endblock %}


{% block content_title %}
<h3>Weapons</h3>
{% endblock %}


{% block content %}
<table>
    <thead>
        <tr>
            <th>name</th>
            <th>total kills</th>
        </tr>
    </thead>
    <tbody>
{% for object in object_list %}
        <tr class="{% cycle "even" "odd" %}">
            <td><a href="{{object.get_absolute_url}}">{{object.ut_name}}</td>
            <td>{{object.kill_set.count}}</a></td>
        </tr>
{% endfor %}
    </tbody>
</table>
{% endblock %}